### PR TITLE
Adding HTML Editor for Leader Notes

### PR DESCRIPTION
**Pull request by pixelsaurus**

### CODE REVIEW

**Review by dylanmartin — COMMENTED** [review]
I think editing and rendering markdown vs html makes more sense here. Open to discussing.
Here are my thoughts:
- Markdown has simpler, less verbose syntax that is readable even without rendering.
- Markdown is already being used elsewhere in the app
- Most markdown renderers support embedding HTML

This editor looks good:
https://www.npmjs.com/package/@uiw/react-md-editor

**Comment by dylanmartin** [comment]
The markdown editor includes a toolbar and a preview panel, which allows users to see and edit the markdown syntax directly. Unlike the HTML editor, which obscures the source code, markdown syntax is simple enough that it doesn’t need to be hidden.

Markdown is really tailored for this kind of use case—it’s easy to read and write even without rendering. Additionally, using markdown supports easy copy-pasting with preserved formatting, especially for elements like lists. In contrast, the HTML editor hides the source and likely has its own method of handling rich text.

image  
image

**Comment by pixelsaurus** [comment]
React Quill is just meant for typing text and rendering the result to the page (which is HTML), in the above solution there is no intermediary step of having to understand/learn/type Markdown, which I think is unnecessary for simply adding some quick notes.

I don't agree with using Markdown for this use case as I believe it is inefficient middle step. The use case is: Type some quick notes with the ability to make simple formatting choices ie: Bold, Italic, Lists. That's all. Let's use the correct tool for the job. 

We use Markdown in one case for Computation Notes with the assumption that a Computation Author has some knowledge regarding coding and syntax, and in possible anticipation of someone perhaps copying and pasting a readme.md file from Github or similar. Computation Notes has more elaborate formatting needs than Leader notes, and we shouldn't make the same assumption of expertise for the average Consortium Leader that we do of a Computation Author.

**Comment by dylanmartin** [comment]
I’m on board with using HTML here. I agree that ease of use and accessibility for non-technical users is important, and a WYSIWYG editor works well for that purpose.

The alternative I would propose is plaintext with optional markdown support, which has some distinct advantages:

- **RAW HTML is Visually Cumbersome**: Without rendering, HTML can be hard to read and manage in its raw form.
  
- **Copy-Paste with Rich Text is a Pain**: Copying and pasting rich text can often lead to issues where formatting gets stripped unexpectedly, sometimes without warning or user control.

- **Markdown’s Advantages**:
  - **Portability**: Markdown preserves formatting consistently across platforms, with no dependency on rendering. It’s also readable in raw form, making it versatile and reliable.
  - **Simplicity**: Markdown’s syntax is straightforward, so users can easily add basic styling without needing a complex interface.

**Pull request closed without merging**
